package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.ISBNtarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.03.07 11:05:15 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class ISBNtarkistusTest {



  // Generated by ComTest BEGIN
  /** testIsbnTarkistusnumero20 */
  @Test
  public void testIsbnTarkistusnumero20() {    // ISBNtarkistus: 20
    assertEquals("From: ISBNtarkistus line: 21", 4, isbnTarkistusnumero("978-951-0-43361-4")); 
    assertEquals("From: ISBNtarkistus line: 22", 4, isbnTarkistusnumero("978-951-0-43361-")); 
    assertEquals("From: ISBNtarkistus line: 23", 4, isbnTarkistusnumero("978-951-0-43361")); 
    assertEquals("From: ISBNtarkistus line: 24", 6, isbnTarkistusnumero("9789510403686")); 
    assertEquals("From: ISBNtarkistus line: 25", 6, isbnTarkistusnumero("978-1-4732-1189")); 
  } // Generated by ComTest END
}