package kirjasto.test;
// Generated by ComTest BEGIN
import java.util.List;
import java.util.ArrayList;
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.25 15:52:02 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AsiasanatTest {



  // Generated by ComTest BEGIN
  /** testAnna52 */
  @Test
  public void testAnna52() {    // Asiasanat: 52
    Asiasanat asiasanat = new Asiasanat(); 
    Asiasana as1 = new Asiasana(); 
    Asiasana as2 = new Asiasana(); 
    Asiasana as3 = new Asiasana(); 
    asiasanat.lisaa(as1); 
    asiasanat.lisaa(as2); 
    asiasanat.lisaa(as3); 
    Asiasana haettu = asiasanat.anna(2); 
    assertEquals("From: Asiasanat line: 61", as2.toString(), haettu.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnkoJo99 */
  @Test
  public void testOnkoJo99() {    // Asiasanat: 99
    Asiasanat asiasanat = new Asiasanat(); 
    Asiasana kissa = new Asiasana(); 
    kissa.setAsiasana("kissa"); 
    asiasanat.lisaa(kissa); 
    Asiasana koira = new Asiasana(); 
    koira.setAsiasana("koira"); 
    asiasanat.lisaa(koira); 
    Asiasana kana = new Asiasana(); 
    kana.setAsiasana("kana"); 
    asiasanat.lisaa(koira); 
    Asiasana kani = new Asiasana(); 
    kani.setAsiasana("kani"); 
    assertEquals("From: Asiasanat line: 112", null, asiasanat.onkoJo(kani)); 
    assertEquals("From: Asiasanat line: 113", koira, asiasanat.onkoJo(koira)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse133 */
  @Test
  public void testParse133() {    // Asiasanat: 133
    Asiasanat asiasanat = new Asiasanat(); 
    List<Asiasana> lista = asiasanat.parse("kissa, koira, kana", ','); 
    Asiasana kissa = new Asiasana(); 
    kissa.setAsiasana("kissa"); 
    Asiasana koira = new Asiasana(); 
    koira.setAsiasana("koira"); 
    Asiasana kana = new Asiasana(); 
    kana.setAsiasana("kana"); 
    ArrayList<Asiasana> toinenLista = new ArrayList<Asiasana>(); 
    toinenLista.add(kissa); 
    toinenLista.add(koira); 
    toinenLista.add(kana); 
    assertEquals("From: Asiasanat line: 148", toinenLista.toString(), lista.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedosto238 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedosto238() throws SailoException {    // Asiasanat: 238
    Asiasanat asiasanat = new Asiasanat(); 
    Asiasana as1 = new Asiasana(), as2 = new Asiasana(); 
    String hakemisto = "testikirjasto"; 
    String tiedNimi = hakemisto + "/tekijat"; 
    File ftied = new File(tiedNimi + ".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    asiasanat.lueTiedosto(tiedNimi); 
    fail("Asiasanat: 251 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    asiasanat.lisaa(as1); 
    asiasanat.lisaa(as2); 
    asiasanat.tallenna(); 
    asiasanat = new Asiasanat(); 
    asiasanat.lueTiedosto(tiedNimi); 
    assertEquals("From: Asiasanat line: 257", as1.toString(), asiasanat.anna(0).toString()); 
    assertEquals("From: Asiasanat line: 258", as2.toString(), asiasanat.anna(1).toString()); 
    asiasanat.lisaa(as2); 
    asiasanat.tallenna(); 
    assertEquals("From: Asiasanat line: 261", true, ftied.delete()); 
    File fbak = new File(tiedNimi + ".bak"); 
    assertEquals("From: Asiasanat line: 263", true, fbak.delete()); 
    assertEquals("From: Asiasanat line: 264", true, dir.delete()); 
  } // Generated by ComTest END
}