package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.18 10:47:54 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AsiasanaTest {



  // Generated by ComTest BEGIN
  /** testGetAsiasana40 */
  @Test
  public void testGetAsiasana40() {    // Asiasana: 40
    Asiasana egypti = new Asiasana(); 
    egypti.lisaaEgypti(); 
    egypti.rekisteroi(); 
    { String _l_=egypti.getAsiasana(),_r_="Egypti .*"; if ( !_l_.matches(_r_) ) fail("From: Asiasana line: 44" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi72 */
  @Test
  public void testRekisteroi72() {    // Asiasana: 72
    Asiasana egypti = new Asiasana(); 
    assertEquals("From: Asiasana line: 74", 0, egypti.getId()); 
    egypti.rekisteroi(); 
    Asiasana egypti2 = new Asiasana(); 
    egypti2.rekisteroi(); 
    int id1 = egypti.getId(); 
    int id2 = egypti2.getId(); 
    assertEquals("From: Asiasana line: 80", id2-1, id1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse115 */
  @Test
  public void testParse115() {    // Asiasana: 115
    Asiasana asiasana = new Asiasana(); 
    asiasana.parse("   4  |  kissa"); 
    assertEquals("From: Asiasana line: 118", 4, asiasana.getId()); 
    assertEquals("From: Asiasana line: 119", "4|kissa", asiasana.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString133 */
  @Test
  public void testToString133() {    // Asiasana: 133
    Asiasana asiasana = new Asiasana(); 
    asiasana.parse("   4  |  kissa"); 
    assertEquals("From: Asiasana line: 136", "4|kissa", asiasana.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo184 */
  @Test
  public void testCompareTo184() {    // Asiasana: 184
    Asiasana as1 = new Asiasana(); 
    as1.setAsiasana("kissa"); 
    Asiasana as2 = new Asiasana(); 
    as2.setAsiasana("koira"); 
    Asiasana as3 = new Asiasana(); 
    as3.setAsiasana("Kissa"); 
    assertEquals("From: Asiasana line: 191", -1, as1.compareTo(as2)); 
    assertEquals("From: Asiasana line: 192", 0, as1.compareTo(as3)); 
  } // Generated by ComTest END
}