package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.03 14:20:33 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AsiasanaKirjaPariTest {



  // Generated by ComTest BEGIN
  /** testParse70 */
  @Test
  public void testParse70() {    // AsiasanaKirjaPari: 70
    AsiasanaKirjaPari akp = new AsiasanaKirjaPari(); 
    akp.parse("   4  |  78 "); 
    assertEquals("From: AsiasanaKirjaPari line: 73", 78, akp.getKirjaId()); 
    assertEquals("From: AsiasanaKirjaPari line: 74", 4, akp.getAsiasanaId()); 
    assertEquals("From: AsiasanaKirjaPari line: 75", "4|78", akp.toString()); 
  } // Generated by ComTest END
}