package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.25 14:43:55 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi38 */
  @Test
  public void testGetNimi38() {    // Kirja: 38
    Kirja sinuhe = new Kirja(); 
    sinuhe.taytaSinuhe(1); 
    { String _l_=sinuhe.getNimi(),_r_="Sinuhe Egyptiläinen .*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 41" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta113 */
  @Test
  public void testAseta113() {    // Kirja: 113
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 115", null, kirja.aseta(2, "Kissanhoito-opas")); 
    assertEquals("From: Kirja line: 116", "Vuoden on oltava numero", kirja.aseta(3, "Kissanhoito-opas")); 
    assertEquals("From: Kirja line: 117", null, kirja.aseta(3, "2019")); 
    assertEquals("From: Kirja line: 118", null, kirja.aseta(3, "2019")); 
    assertEquals("From: Kirja line: 119", "Virheellinen ISBN", kirja.aseta(5, "978-952-6-5124-13")); 
    assertEquals("From: Kirja line: 120", null, kirja.aseta(7, "98.3")); 
    assertEquals("From: Kirja line: 121", "Luokan on oltava numero. Desimaalierottimena on piste.", kirja.aseta(7, "98,3")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi194 */
  @Test
  public void testRekisteroi194() {    // Kirja: 194
    Kirja sinuhe = new Kirja(); 
    assertEquals("From: Kirja line: 196", 0, sinuhe.getId()); 
    sinuhe.rekisteroi(); 
    Kirja sinuhe2 = new Kirja(); 
    sinuhe2.rekisteroi(); 
    int id1 = sinuhe.getId(); 
    int id2 = sinuhe2.getId(); 
    assertEquals("From: Kirja line: 202", id2-1, id1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString260 */
  @Test
  public void testToString260() {    // Kirja: 260
    Kirja kirja = new Kirja(); 
    kirja.parse("   5  | 4 | Sinuhe Egyptiläinen     |   2007"); 
    assertEquals("From: Kirja line: 263", true, kirja.toString().startsWith("5|4|Sinuhe Egyptiläinen|2007|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse285 */
  @Test
  public void testParse285() {    // Kirja: 285
    Kirja kirja = new Kirja(); 
    kirja.parse("   5  | 3| Sinuhe Egyptiläinen     |   2007"); 
    assertEquals("From: Kirja line: 288", 5, kirja.getId()); 
    assertEquals("From: Kirja line: 289", true, kirja.toString().startsWith("5|3|Sinuhe Egyptiläinen|2007|")); 
    kirja.rekisteroi(); 
    int n = kirja.getId(); 
    kirja.parse(""+(n+20)); 
    kirja.rekisteroi(); 
    assertEquals("From: Kirja line: 294", n+20+1, kirja.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetIsbn384 */
  @Test
  public void testSetIsbn384() {    // Kirja: 384
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 386", null, kirja.setIsbn("978-951-1-32256-6")); 
    assertEquals("From: Kirja line: 387", "Virheellinen ISBN", kirja.setIsbn("978-951-1-32256-5")); 
    assertEquals("From: Kirja line: 388", "Virheellinen ISBN", kirja.setIsbn("978-951-1-3225")); 
  } // Generated by ComTest END
}