package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.26 09:55:49 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TekijaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi34 */
  @Test
  public void testRekisteroi34() {    // Tekija: 34
    Tekija mika = new Tekija(); 
    assertEquals("From: Tekija line: 36", 0, mika.getId()); 
    mika.rekisteroi(); 
    Tekija mika2 = new Tekija(); 
    mika2.rekisteroi(); 
    int id1 = mika.getId(); 
    int id2 = mika2.getId(); 
    assertEquals("From: Tekija line: 42", id2-1, id1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString117 */
  @Test
  public void testToString117() {    // Tekija: 117
    Tekija tekija = new Tekija(); 
    tekija.parse("   4  |  Mika|  Waltari"); 
    assertEquals("From: Tekija line: 120", true, tekija.toString().startsWith("4|Mika|Waltari")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse134 */
  @Test
  public void testParse134() {    // Tekija: 134
    Tekija tekija = new Tekija(); 
    tekija.parse("   4  |  Mika|  Waltari"); 
    assertEquals("From: Tekija line: 137", 4, tekija.getId()); 
    assertEquals("From: Tekija line: 138", true, tekija.toString().startsWith("4|Mika|Waltari")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse154 */
  @Test
  public void testParse154() {    // Tekija: 154
    Tekija tekija = new Tekija(); 
    tekija.parse("Pakkanen, Pekka", ','); 
    assertEquals("From: Tekija line: 157", "Pakkanen", tekija.getSukunimi()); 
    assertEquals("From: Tekija line: 158", "Pekka", tekija.getEtunimi()); 
    assertEquals("From: Tekija line: 159", "Pakkanen, Pekka", tekija.getSukunimiEtunimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo174 */
  @Test
  public void testCompareTo174() {    // Tekija: 174
    Tekija t1 = new Tekija(); 
    t1.setEtunimi("Kalle"); 
    t1.setSukunimi("Päätalo"); 
    Tekija t2 = new Tekija(); 
    t2.setEtunimi("Kille"); 
    t2.setSukunimi("Puutalo"); 
    Tekija t3 = new Tekija(); 
    t3.setEtunimi("kalle"); 
    t3.setSukunimi("päätalo"); 
    assertEquals("From: Tekija line: 184", -1, t1.compareTo(t2)); 
    assertEquals("From: Tekija line: 185", 0, t1.compareTo(t3)); 
  } // Generated by ComTest END
}