package kirjasto.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.26 10:00:30 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TekijatTest {



  // Generated by ComTest BEGIN
  /** testOnkoJo48 */
  @Test
  public void testOnkoJo48() {    // Tekijat: 48
    Tekijat tekijat = new Tekijat(); 
    Tekija mika = new Tekija(); 
    mika.setEtunimi("Mika"); 
    mika.setSukunimi("Waltari"); 
    Tekija kalle = new Tekija(); 
    kalle.setEtunimi("Kalle"); 
    kalle.setSukunimi("Päätalo"); 
    Tekija enni = new Tekija(); 
    enni.setEtunimi("Enni"); 
    enni.setSukunimi("Mustonen"); 
    Tekija pirjo = new Tekija(); 
    pirjo.setEtunimi("Pirjo"); 
    pirjo.setSukunimi("Tuominen"); 
    tekijat.lisaa(mika); tekijat.lisaa(kalle); tekijat.lisaa(enni); 
    assertEquals("From: Tekijat line: 63", mika, tekijat.onkoJo(mika)); 
    assertEquals("From: Tekijat line: 64", null, tekijat.onkoJo(pirjo)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedosto198 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedosto198() throws SailoException {    // Tekijat: 198
    Tekijat tekijat = new Tekijat(); 
    Tekija tekija1 = new Tekija(), tekija2 = new Tekija(); 
    String hakemisto = "testikirjasto"; 
    String tiedNimi = hakemisto + "/tekijat"; 
    File ftied = new File(tiedNimi + ".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    tekijat.lueTiedosto(tiedNimi); 
    fail("Tekijat: 211 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    tekijat.lisaa(tekija1); 
    tekijat.lisaa(tekija2); 
    tekijat.tallenna(); 
    tekijat = new Tekijat(); 
    tekijat.lueTiedosto(tiedNimi); 
    assertEquals("From: Tekijat line: 217", tekija1.toString(), tekijat.anna(0).toString()); 
    assertEquals("From: Tekijat line: 218", tekija2.toString(), tekijat.anna(1).toString()); 
    tekijat.lisaa(tekija2); 
    tekijat.tallenna(); 
    assertEquals("From: Tekijat line: 221", true, ftied.delete()); 
    File fbak = new File(tiedNimi + ".bak"); 
    assertEquals("From: Tekijat line: 223", true, fbak.delete()); 
    assertEquals("From: Tekijat line: 224", true, dir.delete()); 
  } // Generated by ComTest END
}